version: '3.9'

services:
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      PGHOST: host.docker.internal
      PGUSER: magz
      PGDATABASE: todo_db
      PGPASSWORD: password
      PGPORT: "5432"
